spring.application.name=pagilaapp

# Override if necessary (the default is 8080)
server.port=8088

spring.datasource.url=jdbc:postgresql://localhost:5432/pagila
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

# See https://discourse.hibernate.org/t/entitygraph-has-limit-in-depth-levels-for-hibernate-6-1-6-final-and-6-1-7-final/7439/9
# Note that the default is 2
spring.jpa.properties.hibernate.max_fetch_depth=4

spring.jpa.open-in-view=false

logging.level.org.jooq.tools.LoggerListener=DEBUG

logging.level.eu.cdevreeze.pagilaapp.service=DEBUG

# If useJooq is true, jOOQ service implementations are used. Otherwise, JPA service implementations are used.
useJooq=false

# Security (mainly authentication and authorization)

spring.security.oauth2.client.registration.keycloak.provider=myrealm
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.client-id=myclient
spring.security.oauth2.client.registration.keycloak.client-secret=myclient-secret
spring.security.oauth2.client.registration.keycloak.scope=openid

spring.security.oauth2.client.provider.myrealm.issuer-uri=http://localhost:8080/realms/myrealm
spring.security.oauth2.client.provider.myrealm.authorization-uri=http://localhost:8080/realms/myrealm/protocol/openid-connect/auth
spring.security.oauth2.client.provider.myrealm.token-uri=http://localhost:8080/realms/myrealm/protocol/openid-connect/token
spring.security.oauth2.client.provider.myrealm.user-info-uri=http://localhost:8080/realms/myrealm/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.myrealm.jwk-set-uri=http://localhost:8080/realms/myrealm/protocol/openid-connect/certs
